FROM node:12-alpine AS build-stage

WORKDIR /react-app
COPY . .

# You have to set this because it should be set during build time.
#ENV REACT_APP_BASE_URL=http://www.alaga.tech/

RUN npm ci --only=production

# Build our React App
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build-stage /react-app/build/ /usr/share/nginx/html/
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]